services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  T3easy\Filecategories\:
    resource: '../Classes/*'

  T3easy\Filecategories\Aspect\FileCategoryAspect:
    tags:
    - name: event.listener
      identifier: 't3easy-filecategories'
      method: 'addCategoriesToMetadata'
      event: TYPO3\CMS\Core\Resource\Event\EnrichFileMetaDataEvent
      after: 'typo3-frontend/overlay'