name: PHP Coding Standards Fixer

on:
  push:
  pull_request:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install PHP Coding Standards Fixer
      run: composer install --working-dir=Tools/php-cs-fixer --no-progress
    - name: Run PHP Coding Standards Fixer
      run: Tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run --diff