name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - typo3: "^10.4"
          php: "7.4"
        - typo3: "^11.5"
          php: "7.4"
        - typo3: "^11.5"
          php: "8.0"
        - typo3: "^11.5"
          php: "8.1"
    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP ${{ matrix.php }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: none
    - name: Require TYPO3 ${{ matrix.typo3 }}
      run: composer require --no-interaction --no-update "typo3/cms-core:${{ matrix.typo3 }}"
    - name: Install dependencies
      run: composer install --no-interaction --no-progress
    - name: Run PHP tests
      run: composer run-script tests